#!/bin/bash
cd /usr/local/bin/
# Cleanup Existing Entries
sudo rm check
sudo rm chkmov
sudo rm chkrun
sudo rm dist
sudo rm distribute
sudo rm DownloadMonitor
sudo rm epinfo
sudo rm manage_trakt
sudo rm parsem
sudo rm parses
sudo rm newshows
sudo rm renamemovies
sudo rm renameseries
sudo rm renmov
sudo rm resetfolders
sudo rm rs
sudo rm X11VNC-Start
# GRUMPY ONLY
sudo rm rpyc_server
sudo rm syncrmt
sudo rm syncrmt_tst
sudo rm startmonitor
sudo rm syncstart
sudo rm UpdateXBMC
# Remove after Full Conversion
sudo rm movies
sudo rm build_links
sudo rm adduser.py
sudo rm chkAVI
sudo rm chkvideo
sudo rm dbldownload
sudo rm dbldfiles
sudo rm getnew
sudo rm getnew_ui
sudo rm getnew3
sudo rm getnew.glade
sudo rm series
sudo rm series.glade
sudo rm startdeluged
sudo rm X11VNC-Start.py

# Add New Entries
sudo ln -s /usr/local/lib/python2.7/dist-packages/dadvision/series/check.py			check
sudo ln -s /usr/local/lib/python2.7/dist-packages/dadvision/library/gettmdb.py	            	chkmov
sudo ln -s /usr/local/lib/python2.7/dist-packages/dadvision/utilities/chkrun.py	            	chkrun
sudo ln -s /usr/local/lib/python2.7/dist-packages/dadvision/library/distribute.py 	    	distribute
sudo ln -s /usr/local/lib/python2.7/dist-packages/dadvision/library/distribute.py 	    	dist
sudo ln -s /usr/local/lib/python2.7/dist-packages/dadvision/library/DownloadMonitor.py 	    	DownloadMonitor
sudo ln -s /usr/local/lib/python2.7/dist-packages/dadvision/library/series/episodeinfo.py    	epinfo
sudo ln -s /usr/local/lib/python2.7/dist-packages/dadvision/library/trakttv/manage.py    	manage_trakt
sudo ln -s /usr/local/lib/python2.7/dist-packages/dadvision/library/movies/fileparser.py     	parsem
sudo ln -s /usr/local/lib/python2.7/dist-packages/dadvision/library/series/fileparser.py     	parses
sudo ln -s /usr/local/lib/python2.7/dist-packages/dadvision/library/series/newshows.py 	    	newshows
sudo ln -s /usr/local/lib/python2.7/dist-packages/dadvision/library/movie/rename.py 	    	renamemovies
sudo ln -s /usr/local/lib/python2.7/dist-packages/dadvision/library/series/rename.py 	    	renameseries
sudo ln -s /usr/local/lib/python2.7/dist-packages/dadvision/utilities/reset_folder_dates.py 	resetfolders
sudo ln -s /usr/local/lib/python2.7/dist-packages/dadvision/utilities/X11VNC-Start.py       	X11VNC-Start
# GRUMPY ONLY
sudo ln -s /usr/local/lib/python2.7/dist-packages/dadvision/library/rpyc_server.py 	    	rpyc_server
sudo ln -s /usr/local/lib/python2.7/dist-packages/dadvision/utilities/startmonitor	    	startmonitor
sudo ln -s /usr/local/lib/python2.7/dist-packages/dadvision/library/syncrmt.py 		    	syncrmt
sudo ln -s /srv/Shared/Programming/PycharmProjects/DadVision/dadvision/library/syncrmt.py 	syncrmt_tst
sudo ln -s /usr/local/lib/python2.7/dist-packages/dadvision/utilities/syncstart		    	syncstart
sudo ln -s /usr/local/lib/python2.7/dist-packages/dadvision/utilities/UpdateXBMC.py 	    	UpdateXBMC
