#!/bin/bash
cd /usr/local/bin/
# Cleanup Existing Entries
sudo rm build_links
sudo rm chkrun
sudo rm dist
sudo rm distribute
sudo rm DownloadMonitor
sudo rm getnew
sudo rm getnew_ui
sudo rm movies
sudo rm newshows
sudo rm renamemovies
sudo rm renameseries
sudo rm renmov
sudo rm resetfolders
sudo rm rs
sudo rm series.glade
sudo rm series
sudo rm startdeluged
sudo rm startmonitor
sudo rm X11VNC-Start
sudo rm X11VNC-Start.py
# GRUMPY ONLY
sudo rm rpyc_server
sudo rm syncrmt
sudo rm syncstart
sudo rm UpdateXBMC
# Remove after Full Conversion
sudo rm adduser.py
sudo rm chkAVI
sudo rm chkvideo
sudo rm dbldownload
sudo rm dbldfiles
sudo rm getnew3
sudo rm getnew.glade

# Add New Entries
sudo ln -s /usr/local/lib/python2.7/dist-packages/dadvision/utilities/setup/build_links     build_links
sudo ln -s /usr/local/lib/python2.7/dist-packages/dadvision/utilities/chkrun.py	            chkrun
sudo ln -s /usr/local/lib/python2.7/dist-packages/dadvision/library/distribute.py 	    distribute
sudo ln -s /usr/local/lib/python2.7/dist-packages/dadvision/library/distribute.py 	    dist
sudo ln -s /usr/local/lib/python2.7/dist-packages/dadvision/library/DownloadMonitor.py 	    DownloadMonitor
sudo ln -s /usr/local/lib/python2.7/dist-packages/dadvision/library/getnew/getnew.py 	    getnew
sudo ln -s /usr/local/lib/python2.7/dist-packages/dadvision/library/getnew/getnew_ui.py	    getnew_ui
sudo ln -s /usr/local/lib/python2.7/dist-packages/dadvision/library/series/newshows.py 	    newshows
sudo ln -s /usr/local/lib/python2.7/dist-packages/dadvision/library/movie/rename.py 	    renamemovies
sudo ln -s /usr/local/lib/python2.7/dist-packages/dadvision/library/series/rename.py 	    renameseries
sudo ln -s /usr/local/lib/python2.7/dist-packages/dadvision/library/movie/rename.py 	    renmov
sudo ln -s /usr/local/lib/python2.7/dist-packages/dadvision/utilities/reset_folder_dates.py resetfolders
sudo ln -s /usr/local/lib/python2.7/dist-packages/dadvision/library/series/rename.py	    rs
sudo ln -s /usr/local/lib/python2.7/dist-packages/dadvision/library/series/newshows.py      newshows
sudo ln -s /usr/local/lib/python2.7/dist-packages/dadvision/library/series/series.glade     series.glade
sudo ln -s /usr/local/lib/python2.7/dist-packages/dadvision/library/series/series.py	    series
sudo ln -s /usr/local/lib/python2.7/dist-packages/dadvision/utilities/startdeluged	    startdeluged
sudo ln -s /usr/local/lib/python2.7/dist-packages/dadvision/utilities/startmonitor	    startmonitor
sudo ln -s /usr/local/lib/python2.7/dist-packages/dadvision/utilities/X11VNC-Start.py       X11VNC-Start
# GRUMPY ONLY
sudo ln -s /usr/local/lib/python2.7/dist-packages/dadvision/library/rpyc_server.py 	    rpyc_server
sudo ln -s /usr/local/lib/python2.7/dist-packages/dadvision/library/syncrmt.py 		    syncrmt
sudo ln -s /usr/local/lib/python2.7/dist-packages/dadvision/utilities/syncstart		    syncstart
sudo ln -s /usr/local/lib/python2.7/dist-packages/dadvision/utilities/UpdateXBMC.py 	    UpdateXBMC
